### ISSUE TITLE
APNv2

### ISSUE THREAD

**Issue by onpaws** [calonso/rails-push-notifications#12]
What I like about this gem is that it targets both Apple and Android platforms in one place. 

Seeing as Apple rolled out and now recommends [HTTP/2 based APNv2](https://developer.apple.com/videos/play/wwdc2016/724/) and Google now [recommends Firebase](https://firebase.google.com/docs/cloud-messaging/), I'm curious if there's a timeline for supporting these developments?

**Comment by calonso** [comment]
Hi @onpaws 

Glad you find this gem interesting!! Currently I had no plans for improvement, but I'm happy to help and work with you if you fancy leading this change!! We definitely need contributors for this project.

Are you up for it?

Regards

**Comment by calonso** [comment]
Closing this as stale, please reopen if necessary.

**Comment by onpaws** [comment]
Thanks for the polite close. 

In the end we had to table push notifications but may revisit in the future.

I see [Rpush](https://github.com/rpush/rpush/pull/315) added tentative APNSv2 support - perhaps there's useful info for a future implementor to check out what's happening there?
