### ISSUE TITLE
this gem works with FCM? 

### ISSUE THREAD

**Issue by mquispe1185** [calonso/rails-push-notifications#15]
if yes, how should I implement it with firebase cloud messaging? or its outdated? im using rails 5. thanks in advance..

**Comment by calonso** [comment]
Hi @mquispe1185 I'm not sure how this may fit with FCM but I think it should work as, in the end, firebase uses the native messaging protocol of the platform, which is where the ruby-push-notifications gem connects you with.

**Comment by calonso** [comment]
Closing as stale... Please reopen if required.
