### ISSUE TITLE
Data for GCM is not text

### ISSUE THREAD

**Issue by ArnaudRemi** [calonso/rails-push-notifications#16]
Hello.

Just lost few hours.
The data object for GCM is not using "text" key but "message".

Hope it will help.

**Comment by calonso** [comment]
Hi @ArnaudRemi thanks for your help. Could you please add a bit more context on it? Also, would you be up for fixing it? I'll help with everything you may need.

**Comment by ArnaudRemi** [comment]
Hi.

Sorry, I should have done a PR.
https://github.com/calonso/rails-push-notifications/pull/17

thanks for your work.

**Comment by calonso** [comment]
Thanks @ArnaudRemi . Closing this as #17 is merged
