### ISSUE TITLE
Pushkit notifications

### ISSUE THREAD

**Issue by juangz** [calonso/rails-push-notifications#18]
Hello,

I need to send push notifications for voip applications to start a call. Does it support pushkit? is there any WO to do it?

https://developer.apple.com/library/content/documentation/Performance/Conceptual/EnergyGuide-iOS/OptimizeVoIP.html

Thanks in advance

**Comment by calonso** [comment]
I don't think that is supported ATM, but we're always happy to have more features and contributors. I will help you as much as I can if you decide to go for it and implement it.

Regards

**Comment by calonso** [comment]
Closing as stale... Please reopen if required
