### ISSUE TITLE
How to handle badge count for multiple destinations

### ISSUE THREAD

**Issue by brahamshakti** [calonso/rails-push-notifications#5]
Hi You created awesome gem but in your gem and in APNS code

app = <Your Apple app>
notification = app.notifications.create(
  destinations: [
    'Your first destination token',
    'Your second destination token'
  ],
  data: { aps: { alert: 'Hello APNS World!', sound: 'true', badge: 1 } }
)

you are sending badge 1 for all destinations but if some one wants to send different badge count for different destinations. How did you handle this scenario.

**Comment by calonso** [comment]
Hi @brahamshakti, 

we should handle it as different notifications I'm afraid, doesn't sound like the smartest thing ever but that's how it is so far.

I'd be happy to hear suggestions or even better, pull them!!

**Comment by calonso** [comment]
Closing issue as stale. Please reopen if necessary.
