### ISSUE TITLE
Unable to set sender_id for GCM

### ISSUE THREAD

**Issue by atbyrd** [calonso/rails-push-notifications#6]
When calling ```app.push_notifications``` I get an response error complaining about a mismatch sender id.  ```@results=[#<RubyPushNotifications::GCM::GCMResultError:0x007fdd001805d0 @error="MismatchSenderId">]>,```. From the documentation there doesn't seen to be a way to set this.

**Comment by calonso** [comment]
Hi @atbyrd. This error you're getting is the response received from the GCM system. What I think is happening is that your token is associated with a certain group of senders and you're not sending the message as such. For more info go here: `https://developers.google.com/cloud-messaging/http-server-ref#error-codes` You can see the exact error you're having at row 6 of the table displayed at that link.

Hope it helps.

**Comment by calonso** [comment]
Closing issue as stale. Please reopen is necessary.
