### ISSUE TITLE
Which fields are available?

### ISSUE THREAD

**Issue by gabrieletassoni** [calonso/rails-push-notifications#7]
Hello,
I'm testing this gem with GCM, using on the device the GCM QuickStart, in the notification created I use, as data an hash like this:

`data: { 
      message: self.title
    }`

It correctly sends the notification, which is displayed on the android device, I was looking for a way to set the title and the icon, but can't seem to find one, I tried something like:

`data: { 
     title: "This Title",
      message: self.title
    }`

but it just shows the message? What am I missing?

thank you for the answer,
Gabriele

**Comment by calonso** [comment]
Hi @gabrieletassoni. Rails push notifications gem uses [Ruby Push Notifications](https://github.com/calonso/ruby-push-notifications) to build notifications. In the particular case of GCM the data is appended here: [https://github.com/calonso/ruby-push-notifications/blob/master/lib/ruby-push-notifications/gcm/gcm_notification.rb#L26](https://github.com/calonso/ruby-push-notifications/blob/master/lib/ruby-push-notifications/gcm/gcm_notification.rb#L26) which means that whichever thing you append there should be delivered.

Let me know if you need any further help or you figured out already.
Cheers!

**Comment by gabrieletassoni** [comment]
Many thanks for the answer and the good direction, 
I'll dig more into the payload to be sent and how to manage it client side, I'm using the GCM demo provided by Google, which I think it manages just the :message key, I'll experiment with it to show custom payload fields.

Thanks again,
Gabriele

**Comment by calonso** [comment]
Ok, that's great. 

Let me know if you need anything else and I'll be happy to help.

PS: Once you work out how to add them, could you please add an example to this thread should someone else find it useful? Also an update of the gem's docs/examples would he lovely.

Regards

**Comment by gabrieletassoni** [comment]
Yes, for sure! ^_^ In a couple of days I’d manage to code again on that project and hopefully report back here.

Bye.

**Comment by calonso** [comment]
Closing issue as stale. Any update @gabrieletassoni??

Please reopen when you're ready.
