### ISSUE TITLE
Update Badge number on Android

### ISSUE THREAD

**Issue by raysango** [calonso/rails-push-notifications#8]
Hi, can I change the badge# on Android, I tried to pass the badge attribute but in the notification but nothing happened.

**Comment by raysango** [comment]
Also the notifications sent to the same device are getting overwritten instead of showing two or more notifications it only shows the last notification sent.

**Comment by calonso** [comment]
Hi @raysango I'm not 100% sure how to set the badge on Android devices, and, having a quick Google search on it, it looks like it is something the developer has to manage, check, for example, [this SO thread](http://stackoverflow.com/questions/17811709/android-provide-push-notification-badge-count).

Also, by having a look at [the possible parameters](https://developers.google.com/cloud-messaging/http-server-ref#notification-payload-support) to be sent to Android devices, it looks like the badge is an iOS only thing.

Finally, this gem internally uses [ruby-push-notifications gem](https://github.com/calonso/ruby-push-notifications), and the android payload is actually composed [here](https://github.com/calonso/ruby-push-notifications/blob/master/lib/ruby-push-notifications/gcm/gcm_notification.rb#L26) should you want to try modifying it a little bit for testing purposes.

Hope it helps.

**Comment by calonso** [comment]
Closing issue as stale. Please reopen if necessary
